name: flutter_starter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+9

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.7.0
dependencies:
  flutter:
    sdk: flutter
  #================================= Starter dependencies =================================
  cupertino_icons: ^1.0.8
  responsive_builder: ^0.7.1
  go_router: ^14.6.3
  dio: ^5.7.0
  url_strategy: ^0.2.0
  flutter_secure_storage: ^9.2.4
  signals: ^6.0.2
  flutter_inappwebview: ^6.1.5
  uids_io_sdk_flutter: ^0.0.6
  tenant_replication: ^0.0.2
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^1.0.0
  easy_localization: ^3.0.7+1
  intl: ^0.19.0
  # firebase_core: ^3.12.1
  # firebase_messaging: ^15.2.4
  # firebase_analytics: ^11.4.4
  flutter_local_notifications: 18.0.1
  app_links: ^6.4.0
  change_app_package_name: ^1.5.0
  #================================= Custom Dependencies =================================

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  flutter_launcher_icons: ^0.14.3


flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - lib/custom/lang/
    - lib/html/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

